name: Build and Deploy

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "14"

            - name: Install dependencies
              run: npm install

            - name: Use GitHub Token
              run: echo "REACT_APP_GITHUB_TOKEN=${{ secrets.API_KEY }}" >> .env

            - name: Build and deploy
              run: npm run build
